# Generated by Django 2.0.3 on 2018-03-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationElements',
            new_name='Reservation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservations_text',
            new_name='reservations',
        ),
    ]
